import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for Netflix Data Gateway research
 *
 * This sidebar is auto-generated from the docs-cms/netflix directory structure.
 */
const sidebars: SidebarsConfig = {
  netflixSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from docs-cms/netflix directory
    },
  ],
};

export default sidebars;
