import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for Architecture Decision Records (ADRs)
 *
 * This sidebar is auto-generated from the docs-cms/adr directory structure.
 * Each ADR should have frontmatter with an 'id' field (e.g., id: adr-001).
 */
const sidebars: SidebarsConfig = {
  adrSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from docs-cms/adr directory
    },
  ],
};

export default sidebars;
