import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for Technical Memos
 *
 * This sidebar is auto-generated from the docs-cms/memos directory structure.
 * Each memo should have frontmatter with an 'id' field (e.g., id: memo-001).
 */
const sidebars: SidebarsConfig = {
  memosSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from docs-cms/memos directory
    },
  ],
};

export default sidebars;
