import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for Request for Comments (RFCs)
 *
 * This sidebar is auto-generated from the docs-cms/rfcs directory structure.
 * Each RFC should have frontmatter with an 'id' field (e.g., id: rfc-001).
 */
const sidebars: SidebarsConfig = {
  rfcSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from docs-cms/rfcs directory
    },
  ],
};

export default sidebars;
