apiVersion: prism.io/v1alpha1
kind: PrismPattern
metadata:
  name: test-keda-pattern
  namespace: prism-system
spec:
  pattern: keyvalue
  backend: redis
  image: busybox:latest
  replicas: 1

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

  service:
    type: ClusterIP
    port: 8080

  # KEDA auto-scaling with CPU trigger (simplest test)
  autoscaling:
    enabled: true
    scaler: keda

    minReplicas: 1
    maxReplicas: 5

    pollingInterval: 10
    cooldownPeriod: 30

    # Use CPU trigger (no external dependencies needed)
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "50"
