# Redis Plugin Configuration
# Based on RFC-011 (ACL + password) and ADR-010 (caching layer)

plugin:
  name: redis
  version: 0.1.0

control_plane:
  port: 9092

backend:
  # Redis address (can be overridden by REDIS_ADDRESS env var)
  address: "localhost:6379"

  # Database number
  database: 0

  # ACL authentication (RFC-011)
  username: ""  # Set via env REDIS_USERNAME
  password: ""  # Set via env REDIS_PASSWORD

  # Vault-managed credentials
  vault_enabled: false
  vault_path: "redis/creds/cache-rw"

  # Connection pool settings
  pool_size: 10
  max_retries: 3
  min_idle_conns: 2
  conn_max_idle_time: 300s  # 5 minutes

  # Key prefix for namespacing (e.g., "prism:")
  key_prefix: "prism:"
