name: Acceptance Test Backend (Reusable)

on:
  workflow_call:
    inputs:
      backend:
        description: 'Backend name (e.g., interfaces, redis, nats)'
        required: true
        type: string
      timeout-minutes:
        description: 'Timeout in minutes'
        required: false
        type: number
        default: 15

jobs:
  test:
    name: ${{ inputs.backend }} Tests
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run ${{ inputs.backend }} acceptance tests
        id: test
        run: |
          cd tests/acceptance/${{ inputs.backend }}
          go test -v -coverprofile=coverage.out -coverpkg=github.com/jrepp/prism-data-layer/patterns/... -timeout 10m ./... 2>&1 | tee test-output.txt

      - name: Generate coverage report
        if: always()
        run: |
          cd tests/acceptance/${{ inputs.backend }}
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "### ${{ inputs.backend }} Coverage: $COVERAGE" >> $GITHUB_STEP_SUMMARY

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ inputs.backend }}
          path: tests/acceptance/${{ inputs.backend }}/test-output.txt
          retention-days: 7

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ inputs.backend }}
          path: tests/acceptance/${{ inputs.backend }}/coverage.out
          retention-days: 7
