name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs-cms/**'
      - 'docusaurus/**'
      - 'tooling/build_docs.py'
      - 'tooling/validate_docs.py'
      - '**/*.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs-cms/**'
      - 'docusaurus/**'
      - 'tooling/build_docs.py'
      - 'tooling/validate_docs.py'
      - '**/*.md'
      - '.github/workflows/docs.yml'

# Cancel in-progress runs for the same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Job 0: Generate protobuf code once (new)
  generate-proto:
    name: Generate Protobuf Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate protobuf code
        run: make proto-go

      - name: Upload generated proto code
        uses: actions/upload-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/
          retention-days: 1

  # Job 1: Lint Rust code
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            proxy/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('proxy/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Format Rust code
        run: cd proxy && cargo fmt --all -- --check

      - name: Lint Rust with Clippy
        run: cd proxy && cargo clippy -- -D warnings

  # Job 2: Lint Python code
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Lint Python with ruff
        run: |
          uv run ruff check tooling/
          uv run ruff format --check tooling/

  # Job 3: Lint Go code (parallel by category)
  lint-go:
    name: Lint Go (${{ matrix.category }})
    runs-on: ubuntu-latest
    needs: generate-proto

    strategy:
      fail-fast: false
      matrix:
        category: [critical, security, style, quality]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v2.5.0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache golangci-lint
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ matrix.category }}-${{ hashFiles('.golangci.yml') }}
          restore-keys: |
            ${{ runner.os }}-golangci-lint-${{ matrix.category }}-

      - name: Lint Go - ${{ matrix.category }}
        run: |
          uv run tooling/parallel_lint.py \
            --categories ${{ matrix.category }} \
            --fail-fast

  # Job 2: Test Rust proxy
  test-proxy:
    name: Test Rust Proxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            proxy/target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('proxy/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-
            ${{ runner.os }}-cargo-

      - name: Run Rust tests
        run: cd proxy && cargo test --lib --verbose

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate Rust coverage
        run: cd proxy && cargo tarpaulin --lib --out Xml --output-dir ../

      - name: Upload Rust coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-rust
          path: cobertura.xml
          retention-days: 7
          if-no-files-found: warn

  # Job 3: Test Go patterns
  test-patterns:
    name: Test Go Patterns
    runs-on: ubuntu-latest
    needs: generate-proto

    strategy:
      matrix:
        pattern: [core, memstore, redis, nats]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/

      - name: Run tests for ${{ matrix.pattern }}
        run: cd patterns/${{ matrix.pattern }} && go test -v -cover -race ./...

      - name: Generate coverage report
        run: |
          cd patterns/${{ matrix.pattern }}
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out | grep total | awk '{print "Coverage: " $3}'

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.pattern }}
          path: patterns/${{ matrix.pattern }}/coverage.out
          retention-days: 7

  # Job 4: Integration tests
  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: generate-proto

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/

      - name: Run integration tests
        run: cd tests/integration && go test -v -timeout 5m -race ./...

      - name: Generate coverage report
        run: |
          cd tests/integration
          go test -coverprofile=coverage.out -timeout 5m ./...
          go tool cover -func=coverage.out | grep total | awk '{print "Integration Coverage: " $3}'

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: tests/integration/coverage.out
          retention-days: 7

  # Job 5: Pattern acceptance tests
  # Tests patterns with multiple backend combinations via pattern executable approach
  test-acceptance-patterns:
    name: Pattern Acceptance Tests
    runs-on: ubuntu-latest
    needs: generate-proto

    strategy:
      fail-fast: false
      matrix:
        pattern: [keyvalue, consumer]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: pkg/plugin/gen/

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run ${{ matrix.pattern }} pattern acceptance tests
        run: |
          cd tests/acceptance/patterns/${{ matrix.pattern }}
          go test -v -timeout 15m ./...
        env:
          PRISM_TEST_QUIET: "1"

      - name: Generate coverage report
        run: |
          cd tests/acceptance/patterns/${{ matrix.pattern }}
          go test -coverprofile=coverage.out -timeout 15m ./...
          go tool cover -func=coverage.out | grep total | awk '{print "Pattern Coverage (${{ matrix.pattern }}): " $3}'

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-pattern-${{ matrix.pattern }}
          path: tests/acceptance/patterns/${{ matrix.pattern }}/coverage.out
          retention-days: 7

  # Job 6: Validate documentation
  validate-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docusaurus/package-lock.json

      - name: Install Node dependencies
        run: cd docusaurus && npm ci

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate documentation
        run: uv run tooling/validate_docs.py

  # Job 7: Build all components
  build:
    name: Build All Components
    runs-on: ubuntu-latest
    needs: [generate-proto, lint-rust, lint-python, lint-go, test-proxy, test-patterns, test-integration]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            proxy/target/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('proxy/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-
            ${{ runner.os }}-cargo-

      - name: Build Rust proxy
        run: cd proxy && cargo build --release

      - name: Build Go patterns
        run: |
          cd patterns/memstore && go build -o memstore cmd/memstore/main.go
          cd ../redis && go build -o redis cmd/redis/main.go
          cd ../nats && go build -o nats cmd/nats/main.go

      - name: Upload proxy binary
        uses: actions/upload-artifact@v4
        with:
          name: proxy-binary
          path: proxy/target/release/prism-proxy
          retention-days: 7

      - name: Upload pattern binaries
        uses: actions/upload-artifact@v4
        with:
          name: pattern-binaries
          path: |
            patterns/memstore/memstore
            patterns/redis/redis
            patterns/nats/nats
          retention-days: 7

  # Job 8: Coverage summary
  coverage-summary:
    name: Coverage Summary
    runs-on: ubuntu-latest
    needs: [test-proxy, test-patterns, test-integration, test-acceptance-patterns]
    if: always()

    steps:
      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: build/coverage-reports

      - name: Display coverage summary
        run: |
          {
            echo "## Coverage Summary"
            echo ""
            echo "| Component | Coverage Files |"
            echo "|-----------|----------------|"
            for dir in build/coverage-reports/*/; do
              component=$(basename "$dir")
              if [ -f "$dir/coverage.out" ]; then
                echo "| $component | ✅ Present |"
              else
                echo "| $component | ❌ Missing |"
              fi
            done
          } >> "$GITHUB_STEP_SUMMARY"

  # Job 9: Upload to Codecov
  codecov-upload:
    name: Upload Coverage to Codecov
    runs-on: ubuntu-latest
    needs: [test-proxy, test-patterns, test-integration, test-acceptance-patterns]
    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: build/coverage-reports

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: >-
            build/coverage-reports/coverage-rust/cobertura.xml,
            build/coverage-reports/coverage-core/coverage.out,
            build/coverage-reports/coverage-memstore/coverage.out,
            build/coverage-reports/coverage-redis/coverage.out,
            build/coverage-reports/coverage-nats/coverage.out,
            build/coverage-reports/coverage-integration/coverage.out,
            build/coverage-reports/coverage-pattern-keyvalue/coverage.out,
            build/coverage-reports/coverage-pattern-consumer/coverage.out
          flags: unittests,integration,acceptance
          name: prism-coverage
          fail_ci_if_error: false
          verbose: true

  # Job 10: CI status check (required for merge)
  ci-status:
    name: CI Status Check
    runs-on: ubuntu-latest
    needs: [lint-rust, lint-python, lint-go, test-proxy, test-patterns, test-integration, test-acceptance-patterns, validate-docs, build]
    if: always()

    steps:
      - name: Check all jobs status
        id: ci_check
        run: |
          if [[ "${{ needs.lint-rust.result }}" != "success" ]] || \
             [[ "${{ needs.lint-python.result }}" != "success" ]] || \
             [[ "${{ needs.lint-go.result }}" != "success" ]] || \
             [[ "${{ needs.test-proxy.result }}" != "success" ]] || \
             [[ "${{ needs.test-patterns.result }}" != "success" ]] || \
             [[ "${{ needs.test-integration.result }}" != "success" ]] || \
             [[ "${{ needs.test-acceptance-patterns.result }}" != "success" ]] || \
             [[ "${{ needs.validate-docs.result }}" != "success" ]] || \
             [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "❌ CI pipeline failed"
            echo "status=failure" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "✅ CI pipeline passed"
            echo "status=success" >> $GITHUB_OUTPUT
          fi

      - name: send-ntfy-notification
        if: always() && vars.NTFY_TOPIC != ''
        run: |
          STATUS_EMOJI="${{ steps.ci_check.outputs.status == 'success' && '✅' || '❌' }}"
          STATUS_TEXT="${{ steps.ci_check.outputs.status == 'success' && 'Passed' || 'Failed' }}"
          PRIORITY="${{ steps.ci_check.outputs.status == 'success' && 'default' || 'high' }}"
          TAG="${{ steps.ci_check.outputs.status == 'success' && 'white_check_mark' || 'x' }}"

          # Build job results summary
          JOBS="Lint Rust: ${{ needs.lint-rust.result == 'success' && '✅' || '❌' }}
          Lint Python: ${{ needs.lint-python.result == 'success' && '✅' || '❌' }}
          Lint Go: ${{ needs.lint-go.result == 'success' && '✅' || '❌' }}
          Test Proxy: ${{ needs.test-proxy.result == 'success' && '✅' || '❌' }}
          Test Patterns: ${{ needs.test-patterns.result == 'success' && '✅' || '❌' }}
          Test Integration: ${{ needs.test-integration.result == 'success' && '✅' || '❌' }}
          Test Acceptance (Patterns): ${{ needs.test-acceptance-patterns.result == 'success' && '✅' || '❌' }}
          Validate Docs: ${{ needs.validate-docs.result == 'success' && '✅' || '❌' }}
          Build: ${{ needs.build.result == 'success' && '✅' || '❌' }}"

          curl -H "Title: ${STATUS_EMOJI} CI Pipeline ${STATUS_TEXT}" \
               -H "Priority: ${PRIORITY}" \
               -H "Tags: ${TAG},ci" \
               -H "Click: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
               -d "Repository: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Commit: ${GITHUB_SHA:0:7}
          Author: ${{ github.actor }}

          Job Results:
          ${JOBS}" \
               https://ntfy.sh/${{ vars.NTFY_TOPIC }}
