name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel in-progress runs for the same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Job 0: Generate protobuf code once (new)
  generate-proto:
    name: Generate Protobuf Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate protobuf code
        run: make proto-go

      - name: Upload generated proto code
        uses: actions/upload-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/
          retention-days: 1

  # Job 1: Lint Rust code
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            proxy/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('proxy/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Format Rust code
        run: cd proxy && cargo fmt --all -- --check

      - name: Lint Rust with Clippy
        run: cd proxy && cargo clippy -- -D warnings

  # Job 2: Lint Python code
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Lint Python with ruff
        run: |
          uv run ruff check tooling/
          uv run ruff format --check tooling/

  # Job 3: Lint Go code (parallel by category)
  lint-go:
    name: Lint Go (${{ matrix.category }})
    runs-on: ubuntu-latest
    needs: generate-proto

    strategy:
      fail-fast: false
      matrix:
        category: [critical, security, style, quality]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v2.5.0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache golangci-lint
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ matrix.category }}-${{ hashFiles('.golangci.yml') }}
          restore-keys: |
            ${{ runner.os }}-golangci-lint-${{ matrix.category }}-

      - name: Lint Go - ${{ matrix.category }}
        run: |
          uv run tooling/parallel_lint.py \
            --categories ${{ matrix.category }} \
            --fail-fast

  # Job 2: Test Rust proxy
  test-proxy:
    name: Test Rust Proxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            proxy/target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('proxy/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-
            ${{ runner.os }}-cargo-

      - name: Run Rust tests
        run: cd proxy && cargo test --lib --verbose

  # Job 3: Test Go patterns
  test-patterns:
    name: Test Go Patterns
    runs-on: ubuntu-latest
    needs: generate-proto

    strategy:
      matrix:
        pattern: [core, memstore, redis, nats]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/

      - name: Run tests for ${{ matrix.pattern }}
        run: cd patterns/${{ matrix.pattern }} && go test -v -cover -race ./...

      - name: Generate coverage report
        run: |
          cd patterns/${{ matrix.pattern }}
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out | grep total | awk '{print "Coverage: " $3}'

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.pattern }}
          path: patterns/${{ matrix.pattern }}/coverage.out
          retention-days: 7

  # Job 4: Integration tests
  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: generate-proto

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/

      - name: Run integration tests
        run: cd tests/integration && go test -v -timeout 5m -race ./...

      - name: Generate coverage report
        run: |
          cd tests/integration
          go test -coverprofile=coverage.out -timeout 5m ./...
          go tool cover -func=coverage.out | grep total | awk '{print "Integration Coverage: " $3}'

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: tests/integration/coverage.out
          retention-days: 7

  # Job 5: Acceptance tests (with Docker containers)
  test-acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    needs: generate-proto

    strategy:
      matrix:
        suite: [interfaces, redis, nats]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/

      - name: Run ${{ matrix.suite }} acceptance tests
        run: cd tests/acceptance/${{ matrix.suite }} && go test -v -timeout 10m ./...
        env:
          PRISM_TEST_QUIET: "1"

      - name: Generate coverage report
        run: |
          cd tests/acceptance/${{ matrix.suite }}
          go test -coverprofile=coverage.out -timeout 10m ./...
          go tool cover -func=coverage.out | grep total | awk '{print "Acceptance Coverage (${{ matrix.suite }}): " $3}'

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-acceptance-${{ matrix.suite }}
          path: tests/acceptance/${{ matrix.suite }}/coverage.out
          retention-days: 7

  # Job 6: Validate documentation
  validate-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docusaurus/package-lock.json

      - name: Install Node dependencies
        run: cd docusaurus && npm ci

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate documentation
        run: uv run tooling/validate_docs.py

  # Job 7: Build all components
  build:
    name: Build All Components
    runs-on: ubuntu-latest
    needs: [generate-proto, lint-rust, lint-python, lint-go, test-proxy, test-patterns, test-integration]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download generated proto code
        uses: actions/download-artifact@v4
        with:
          name: proto-generated
          path: patterns/core/gen/

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            proxy/target/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('proxy/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-
            ${{ runner.os }}-cargo-

      - name: Build Rust proxy
        run: cd proxy && cargo build --release

      - name: Build Go patterns
        run: |
          cd patterns/memstore && go build -o memstore cmd/memstore/main.go
          cd ../redis && go build -o redis cmd/redis/main.go
          cd ../nats && go build -o nats cmd/nats/main.go

      - name: Upload proxy binary
        uses: actions/upload-artifact@v4
        with:
          name: proxy-binary
          path: proxy/target/release/proxy
          retention-days: 7

      - name: Upload pattern binaries
        uses: actions/upload-artifact@v4
        with:
          name: pattern-binaries
          path: |
            patterns/memstore/memstore
            patterns/redis/redis
            patterns/nats/nats
          retention-days: 7

  # Job 8: Coverage summary
  coverage-summary:
    name: Coverage Summary
    runs-on: ubuntu-latest
    needs: [test-patterns, test-integration, test-acceptance]
    if: always()

    steps:
      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: coverage-reports

      - name: Display coverage summary
        run: |
          echo "## Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Component | Coverage Files |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|----------------|" >> $GITHUB_STEP_SUMMARY
          for dir in coverage-reports/*/; do
            component=$(basename "$dir")
            if [ -f "$dir/coverage.out" ]; then
              echo "| $component | ✅ Present |" >> $GITHUB_STEP_SUMMARY
            else
              echo "| $component | ❌ Missing |" >> $GITHUB_STEP_SUMMARY
            fi
          done

  # Job 9: CI status check (required for merge)
  ci-status:
    name: CI Status Check
    runs-on: ubuntu-latest
    needs: [lint-rust, lint-python, lint-go, test-proxy, test-patterns, test-integration, test-acceptance, validate-docs, build]
    if: always()

    steps:
      - name: Check all jobs status
        run: |
          if [[ "${{ needs.lint-rust.result }}" != "success" ]] || \
             [[ "${{ needs.lint-python.result }}" != "success" ]] || \
             [[ "${{ needs.lint-go.result }}" != "success" ]] || \
             [[ "${{ needs.test-proxy.result }}" != "success" ]] || \
             [[ "${{ needs.test-patterns.result }}" != "success" ]] || \
             [[ "${{ needs.test-integration.result }}" != "success" ]] || \
             [[ "${{ needs.test-acceptance.result }}" != "success" ]] || \
             [[ "${{ needs.validate-docs.result }}" != "success" ]] || \
             [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "❌ CI pipeline failed"
            exit 1
          else
            echo "✅ CI pipeline passed"
          fi
