name: Lint Workflows

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    name: lint-github-actions
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run-actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          level: error
          fail_on_error: true
